//
//  StubStationService.swift
//  DataLayer
//
//  Created by Arman Arutyunov on 21/03/2018.
//  Copyright © 2018 Arman Arutyunov. All rights reserved.
//

import ModelLayer
import RxSwift

public class StubStationService: StationService {
    public init() {}
    
    public func getStations() -> Observable<[Station]> {
        let bikes = [Bike(id: 23985742, name: "Kona", frameColor: .black),
                     Bike(id: 23948723, name: "KHS", frameColor: .green),
                     Bike(id: 23942934, name: "Giant", frameColor: .red),
                     Bike(id: 45867944, name: "Bianchi", frameColor: .red),
                     Bike(id: 20572984, name: "Electra", frameColor: .green),
                     Bike(id: 01875398, name: "Fuji", frameColor: .black),
                     Bike(id: 13466346, name: "Cinelli", frameColor: .black),
                     Bike(id: 13644039, name: "Foffa", frameColor: .green),
                     Bike(id: 24643631, name: "Haro", frameColor: .red),
                     Bike(id: 51342959, name: "Bianchi", frameColor: .black),
                     Bike(id: 98345395, name: "Electra", frameColor: .red),
                     Bike(id: 37458328, name: "KHS", frameColor: .green),
                     Bike(id: 36134507, name: "Fuji", frameColor: .green),
                     Bike(id: 19326549, name: "Foffa", frameColor: .black),
                     Bike(id: 43810565, name: "Giant", frameColor: .red)]
        
        let stations = [
            Station(id: 24028,
                    location: Location(latitude: 50.158761,
                                       longtitude: 8.687875,
                                       address: "K819, 60435 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 34957,
                    location: Location(latitude: 50.172977,
                                       longtitude: 8.62796,
                                       address: "Max-von-Laue-Straße 13, 60438 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 30498,
                    location: Location(latitude: 50.093772,
                                       longtitude: 8.691139,
                                       address: "Marie-Curie-Straße 13, 60439 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 28339,
                    location: Location(latitude: 50.17176,
                                       longtitude: 8.631976,
                                       address: "Marie-Curie-Straße 9-11, 60439 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 45094,
                    location: Location(latitude: 50.174159,
                                       longtitude: 8.633986,
                                       address: "Altenhöferallee 1, 60438 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 34890,
                    location: Location(latitude: 50.169753,
                                       longtitude: 8.640865,
                                       address: "Lurgiallee 12, 60439 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 23501,
                    location: Location(latitude: 50.164618,
                                       longtitude: 8.642783,
                                       address: "Zeilweg, 60439 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 23598,
                    location: Location(latitude: 50.163567,
                                       longtitude: 8.655008,
                                       address: "Im Uhrig, 60433 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 23492,
                    location: Location(latitude: 50.161501,
                                       longtitude: 8.649583,
                                       address: "Maybachbrücke, 60439 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 56098,
                    location: Location(latitude: 50.158073,
                                       longtitude: 8.654612,
                                       address: "Maybachstraße, 60433 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 28395,
                    location: Location(latitude: 50.160574,
                                       longtitude: 8.661462,
                                       address: "Anne-Frank-Straße, 60433 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 35972,
                    location: Location(latitude: 50.156333,
                                       longtitude: 8.661727,
                                       address: "Nußzeil 60, 60433 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 34598,
                    location: Location(latitude: 50.149763,
                                       longtitude: 8.660312,
                                       address: "Chamissostraße, 60431 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 23598,
                    location: Location(latitude: 50.147038,
                                       longtitude: 8.661626,
                                       address: "Hügelstraße 177, 60431 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 30958,
                    location: Location(latitude: 50.149124,
                                       longtitude: 8.618692,
                                       address: "Heerstraße 9, 60488 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 23895,
                    location: Location(latitude: 50.103084,
                                       longtitude: 8.656932,
                                       address: "Mannheimer Str. 85, 60327 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 12090,
                    location: Location(latitude: 50.101769,
                                       longtitude: 8.681028,
                                       address: "Diesterwegstraße 4, 60594 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 45894,
                    location: Location(latitude: 50.106179,
                                       longtitude: 8.687044,
                                       address: "Elisabethenstraße, 60594 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 65879,
                    location: Location(latitude: 50.100424,
                                       longtitude: 8.685798,
                                       address: "Diesterwegpl., 60594 Frankfurt am Main, Germany"),
                    bikes: bikes),
            Station(id: 23017,
                    location: Location(latitude: 50.093772,
                                       longtitude: 8.691139,
                                       address: "Darmstädter Landstraße, 60598 Frankfurt am Main, Germany"),
                    bikes: bikes)
        ]
        return Observable.just(stations)
    }
}
